name: Bump Version
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      new_ver: ${{ steps.bump.outputs.new_ver }}
      old_ver: ${{ steps.bump.outputs.old_ver }}
      part: ${{ steps.bump.outputs.part }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: bump
        uses: ./
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: v${{ needs.bump-version.outputs.new_ver }}
          release_name: Release v${{ needs.bump-version.outputs.new_ver }}
          draft: false
          prerelease: false
